### ISSUE TITLE
Route and implementation of Bill Show Page

### ISSUE THREAD

**Issue by SevanBadal** [SevanBadal/legibill#9]
- create a UI mockup for a bill show page, share the mockup as a comment on this issue
- implement bill show page Route and File Structure: state/[session]/session/[bill]

**Comment by JonathanTylerWeber** [comment]
Figma Mockup:
https://www.figma.com/design/SOisNJX79ADXlOKRQmMC5T/Legibill?node-id=1669-162202&t=GewO99oxJ2qo4IQo-1

I created one in dark and light mode and took some liberties in the design. You should be able to edit through this link.

**Comment by JonathanTylerWeber** [comment]
There's quite a lot of information from getBill so I just picked what seemed relevant.
https://legiscan.com/gaits/documentation/legiscan
getBill is on page 11 in the docs if you want to check and add or remove data for the page

**Comment by JonathanTylerWeber** [comment]
Made some small edits, I think the url I share relates to the file if I don't invite you. Couldn't find your email to invite you as a collaborator so here's the updated url:
https://www.figma.com/design/SOisNJX79ADXlOKRQmMC5T/Legibill?node-id=1669-162202&t=QTuDI3Fu5GBuu3t4-1
